main: src.Aboot
name: Aboot
version: 1.1.2

commands:
   aboot:
      description: Toggles Aboot for a player.
      usage: /aboot <player>
      permission: Aboot.aboot
      permission-message: You don't have permission.
   abootall:
      description: Toggles Aboot forevery player.
      usage: /abootall
      permission: Aboot.abootall
      permission-message: You don't have permission.


